In [13]:
import numpy
import pandas
import sklearn
from sklearn.neighbors import KNeighborsClassifier
from sklearn import datasets
from sklearn.model_selection import train_test_split

In [14]:
iris_data = datasets.load_iris()
iris_X = iris_data.data
iris_y = iris_data.target

iris_label_0 = iris_X[iris_y == 0,:]
iris_label_1 = iris_X[iris_y == 1,:]
iris_label_2 = iris_X[iris_y == 2,:]

print("Sample from label 0: \n",iris_label_0[:5,:])
print("Sample from label 1: \n",iris_label_1[:5,:])
print("Sample from label 2: \n",iris_label_2[:5,:])


Sample from label 0: 
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
Sample from label 1: 
 [[7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.9 1.5]
 [5.5 2.3 4.  1.3]
 [6.5 2.8 4.6 1.5]]
Sample from label 2: 
 [[6.3 3.3 6.  2.5]
 [5.8 2.7 5.1 1.9]
 [7.1 3.  5.9 2.1]
 [6.3 2.9 5.6 1.8]
 [6.5 3.  5.8 2.2]]


In [16]:
train_X, valid_X, train_y, valid_y = train_test_split(iris_X, iris_y, test_size = 50)

knn_model = KNeighborsClassifier(n_neighbors = 2, p = 2)
knn_model.fit(train_X, train_y)

y_pred = knn_model.predict(valid_X)
print(y_pred)

[1 1 2 0 1 0 2 2 1 1 2 0 1 1 0 1 2 2 2 0 0 2 0 2 0 0 2 0 1 0 1 2 0 1 1 0 0
 2 2 2 1 0 0 2 2 0 1 0 1 1]
