In [1]:
import numpy
from numpy import array

### 1.1 Khởi tạo mảng 1 chiều
#### 1.1.1 Khai báo vector

In [2]:
# help(array)
x = array([1, 2, 3])
print(x)

[1 2 3]


Lưu ý : Numpy không quy ước vector hàng hay vector cột mà chỉ coi một vector là một mảng một chiều. Nếu bạn thực sự muốn có một vector cột, bạn cần phải coi nó là một ma trận có số chiều thứ hai bằng 1, và khi đó phải khai báo với numpy rằng đó là một mảng hai chiều.

### 1.2 Kiểu dữ liệu của array
#### 1.2.1 Kiểu dữ liệu

In [3]:
a = array([1, 2, 3])
print(type(a[0]))

<class 'numpy.int64'>


In [4]:
a = array([1. , 2])
print(type(a[1]))
print(a)

<class 'numpy.float64'>
[1. 2.]


In [5]:
# có thể ép kiểu bằng tham số dtype
a = array([1, 2, 3], dtype = numpy.float64)
print(type(a[0]))
print(a)

<class 'numpy.float64'>
[1. 2. 3.]


### 1.3 Khởi tạo các mảng 1 chiều đặc biệt

#### 1.3.1 Mảng toàn giá trị 0 hoặc 1

Vector 0 là một vector đặc biệt được dùng thường xuyên để khởi tạo. Để khởi tạo một vector 0 có số phần tử là num, ta dùng hàm numpy.zeros

In [6]:
zero_vector = numpy.zeros(3)
print(zero_vector)
# Tương tự với vector toàn 1
# dtype mặc định là numpy.float64
one_vector = numpy.ones(5,dtype = numpy.int64)
print(one_vector)

[0. 0. 0.]
[1 1 1 1 1]


Numpy còn cung cấp hai hàm đặc biệt numpy.zeros_like và numpy.ones_like giúp tạo các mảng 0 và mảng 1 có số chiều giống như chiều của biến số.

In [7]:
a = array([[1, 2, 3],
           [4, 5, 6]])
zero_array = numpy.zeros_like(a)
print(zero_array)
# giống với array a về mọi thứ ví dụ như dtype
# tương tự với ones_like
one_array = numpy.ones_like(a,dtype = numpy.float64)
print(one_array)

[[0 0 0]
 [0 0 0]]
[[1. 1. 1.]
 [1. 1. 1.]]


#### 1.3.2 Cấp số cộng

Tạo mảng các số nguyên từ 0 đến n - 1, ta dùng hàm numpy.arange(n)

In [8]:
numpy.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Tạo mảng các số nguyên từ l --> r - 1, ta dùng hàm numpy.arange(l,r)

In [9]:
numpy.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

Tạo mảng các số nguyên từ l --> r - 1 với công sai d, ta dùng hàm numpy.arange(l,r,d)

In [10]:
numpy.arange(3,10,2)

array([3, 5, 7, 9])

In [11]:
a = numpy.arange(11)
b = numpy.array([2]*11)
print(b**a)

[   1    2    4    8   16   32   64  128  256  512 1024]


### 1.4 Truy cập mảng 1 chiều

#### 1.4.1 Kích thước của mảng
Kích thước của một array x bất kì nói chung được xác định bằng numpy.array.shape <br>
Kết quả trả về là một tuple. Nếu x là một mảng một chiều, kết quả trả về sẽ có dạng (d,) trong đó d, là phần tử đầu tiên-và duy nhất- của tuple này, là số phẩn tử của x

In [12]:
x = array([[1, 2, 3],
           [4, 5, 6]])
print(x.shape)

(2, 3)


#### 1.4.2 Chỉ số
Mỗi thành phần trong mảng 1 chiều tương ứng với một chỉ số. Chỉ số trong numpy, cũng giống như chỉ số trong python, bắt đầu bằng 0. Nếu mảng 1 chiều có d phần tử thì các chỉ số chạy từ 0 đến d - 1

#### 1.4.3 Đọc từng phần tử của vector

#### 1.4.4 Chỉ số ngược
Chú ý: Nếu một mảng một chiều x có số chiều là d thì chỉ số i trong x[i] phải là một số nguyên thoả mãn -d <= i <= d-1. Nếu i nằm ngoài khoảng này, khi sử dụng x[i] sẽ có lỗi index ... is out of bound....

#### 1.4.5 Thay đổi giá trị một phần tử của mảng

### 1.5 Truy cập nhiều phần tử của mảng một chiều

#### 1.5.1 Đọc

In [13]:
arr = numpy.arange(1,11)
index = numpy.array([0,4,7])
print(arr)
print(arr[index])

[ 1  2  3  4  5  6  7  8  9 10]
[1 5 8]


#### 1.5.2 Ghi

In [14]:
# Gán nhiều phần tử cùng lúc
arr[[1, 3, 5]] = -1
print(arr)
# reverve array
rev_arr = arr[::-1]
print(rev_arr)

[ 1 -1  3 -1  5 -1  7  8  9 10]
[10  9  8  7 -1  5 -1  3 -1  1]


#### 1.5.3 Numpy Indexing and Slicing

[Numpy Indexing and Slicing](https://www.tutorialspoint.com/numpy/numpy_indexing_and_slicing.htm)

### 1.6 Tính toán giữa các mảng một chiều và số vô hướng

#### 1.6.1. Phép toán giữa mảng một chiều với một số vô hướng

In [15]:
arr = array([1, 2, 3, 4, 5])
print(arr * 2)
print(3 ** arr)

[ 2  4  6  8 10]
[  3   9  27  81 243]


Chú ý rằng về mặt toán học, không có phép chia cho vector. Tuy nhiên, trong Python, ta vẫn hiểu phép chia một số cho một mảng sẽ tương đương với lấy số đó chia cho từng phần tử trong mảng.

#### 1.6.2 Phép toán giữa hai mảng một chiều
Để có thể tính toán được hai mảng một chiều, số phần tử của hai mảng phải như nhau. Kết quả cũng là một mảng một chiều cùng chiều với hai mảng đó. Các phép toán +, -, *, /, ** sẽ được thực hiện theo kiểu element-wise, tức lấy từng cặp phần tử tương ứng của hai mảng để tính toán rồi lấy kết quả.

In [16]:
x = numpy.array([1, 2, 3])
y = numpy.array([4, 5, 6])
print(x * y)

[ 4 10 18]


#### 1.6.3 Các hàm toán học
Các hàm toán học trong numpy như: numpy.abs, numpy.log, numpy.exp, numpy.sin, numpy.cos, numpy.tan cũng áp dụng lên từng phần tử của mảng. <br> 
Hàm numpy.log là logarit tự nhiên, hàm numpy.exp là hàm $e^x$. <br>
Hàm numpy.sum sẽ trả về tổng các phần tử của mảng một chiều x.

In [17]:
x = numpy.arange(4)
print(numpy.exp(x))

[ 1.          2.71828183  7.3890561  20.08553692]


#### 1.7 Norm 1
![](./images/Norm-1.png)



### 1.8 Softmax cho mảng 1 chiều
![](./images/softmax-1d-array.png)

### 1.9. Tích vô hướng của hai vectors - Norm 2
Tích vô hướng (inner product) của hai vectors x và y có cùng số phần tử được định nghĩa như là: numpy.sum(x*y), tức lấy x nhân với y theo element-wise rồi tính tổng các phần tử:

In [18]:
x = numpy.arange(3)
y = numpy.ones(3)
print(numpy.sum(x*y))

3.0


Hoặc có thể dùng hàm dot

In [19]:
print(x.dot(y))
print(numpy.dot(x, y))

3.0
3.0


### 1.10 min, max, armin, argmax của mảng một chiều

#### 1.10.1 min, max
Để tìm giá trị lớn nhất hay nhỏ nhất của mảng một chiều, chúng ta sử dụng hàm numpy.min hoặc numpy.max.

In [20]:
a = numpy.arange(11)
a[10] = -1000
print(numpy.min(a))
a[0] = 1000
print(numpy.max(a))

-1000
1000


#### 1.10.2 argmin,  argmax
Để tìm chỉ số mà tại đó mảng một chiều đạt giá trị nhỏ nhất hay lớn nhất, ta có thể sử dụng nupy.argmin, hoặc np.argmax

In [21]:
print(numpy.argmax(a))
print(numpy.argmin(a))

0
10


### Softmax II - Phiên bản ổn định
![](./images/softmaxII-1.png)
![](./images/softmaxII-2.png)